---
extends:
  - airbnb-base
  - prettier
rules:
  quotes: ["error", "double"]
  implicit-arrow-linebreak: "off"
  object-curly-newline: "off"
  operator-linebreak: "off"
  comma-dangle: "off"
  no-param-reassign: ["error", {"props": false}]
globals:
  describe: readonly
  test: readonly
  expect: readonly
