name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: jest --coverage
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: run lint
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: run format-check
